### ISSUE TITLE
Big Todo List 

### ISSUE THREAD

**Issue by thelucre** [thelucre/lowrezjam-2016#1]
Must have 
- [x] Finish Map art 
- [x] Split map into layers (bg, paths, objects)
- [x] Layout map with new layers
- [x] Global object mask one map is ready
- [x] Graveyard intro scene (leading to northern map area 
- [x] Animate spirit gate
- [x] Boss 1 Animation (idle, look at player, drink )
- [X] Boss 2 mechanics working (waterways)
- [x] Design boss 2 mechanics
- [x] Boss 2 Animation ()
- [x] Boss 3 Design 
- [x] Boss three animation (intro, idle, move between walk)
- [x] link key items to map object (ring -> teleports, gear -> windmill, ?? -> spirt gate?)
- [x] Get BGM work between map areas 
- [x] Boss death sequence (ghost of family member rising up and fading)
- [x] Title screen
- [x] Animate bridge 
- [ ] cody cloud layers 
- [ ] door key closeup
- [x] wand close up
- [ ] final scene cliff 

Nice to nave
- [x] Grass shakes when collision with player
- [x] Intro car scene animation (car driving, car crash)
- [ ] SFX: Switch trigger 
- [ ] SFX: Teleport
- [x] Better screen wipe animation (billowing smoke or something)
- [ ] Boss 3 death sequence (the sad one)
- [ ] Clouds on each map scene
- [ ] Animated water sprites
- [ ] Cave bridge switch

Great to have 
- [ ] BGM: Intro 
- [ ] BGM: Outro
- [ ] SFX: Water trickle  
- [ ] SFX: Footsteps 
- [ ] SFX: 3 bosses 
- [x] Nice teleport transition (blue flash)
- [x] Boss screenshake
- [ ] Lucre GAMES intro SFX, jingle
